[project]
name = "adk-lab-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.21.0",
    "langchain-community==0.3.20",
    "wikipedia==1.4.0",
]
